/* Generated By:JJTree&JavaCC: Do not edit this line. EG1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int TIMES = 6;
  /** RegularExpression Id. */
  int DIVIDE = 7;
  /** RegularExpression Id. */
  int RECURSION = 8;
  /** RegularExpression Id. */
  int POINT = 9;
  /** RegularExpression Id. */
  int SPACE = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int THEN = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int EGAL = 14;
  /** RegularExpression Id. */
  int LAMBDA = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int VARIABLE = 17;
  /** RegularExpression Id. */
  int LEFT_PAREN = 18;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int LETTER = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"rec\"",
    "\".\"",
    "\" \"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"=\"",
    "\"!\"",
    "<NUMBER>",
    "<VARIABLE>",
    "\"(\"",
    "\")\"",
    "<DIGIT>",
    "<LETTER>",
  };

}
