/* Generated By:JavaCC: Do not edit this line. EG1TreeConstants.java Version 5.0 */
public interface EG1TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVAR = 1;
  public int JJTOPERATEUR = 2;
  public int JJTID = 3;


  public String[] jjtNodeName = {
    "START",
    "VAR",
    "OPERATEUR",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=50cb9f8c19993cf6b3c34ec9d963e959 (do not edit this line) */
